### ISSUE TITLE
Ensure example packages are up-to-date on IPFS

### ISSUE THREAD

**Issue by gnidan** [ethpm/ethpm-spec#100]
Spun out from #99 

Since the EthPM v2 work contains a lot of updates to the example packages, part of the work migrating to v2 should include republishing updated package versions to match the examples in this repository.

**Comment by njgheorghita** [comment]
Thoughts on also updating the solidity version used in the sample contracts?

**Comment by njgheorghita** [comment]
And since we're supporting all content-addressed URIs - do we want to throw a swarm uri somewhere in the mix?

**Comment by pipermerriam** [comment]
For the examples, it *might* be good (and simpler) to convert at least a few of them to have the source code inlined in the package.

**Comment by njgheorghita** [comment]
Would it be better to mix and match these variable fields across the different use-cases. Or would it be better to keep the use-cases pretty homogenous - and then have a specific package for vyper - specific package for in-line source code - specific package for swarm . . .
