### ISSUE TITLE
Simple broken link in documentation

### ISSUE THREAD

**Issue by tjayrush** [ethpm/ethpm-spec#119]
Here:

<img width="953" alt="screen shot 2018-08-13 at 11 19 19 pm" src="https://user-images.githubusercontent.com/5417918/44070002-79ebff58-9f4f-11e8-9830-d97ca17c8191.png">

leads to this missing link: https://github.com/ethpm/ethpm-spec/tree/v2.0.0/spec/package.spec.json

**Comment by gnidan** [comment]
@tjayrush PR opened. Can you confirm it works for you in the [preview](https://ethpm.github.io/ethpm-spec/contrib/ethpm/fix-link/package-spec.html#document-specification) generated for #120?

**Comment by tjayrush** [comment]
Works. Go to  bed.
