### ISSUE TITLE
Dapple implementation process

### ISSUE THREAD

**Issue by mhhf** [ethpm/ethpm-spec#33]
- [x] initialize `epm.json` (Dappfile)
- [ ] package installation
  - [ ] cli commands.
    - [ ] `dapple pkg install ipfs://Qm....`
    - [ ] `dapple pkg install owned` and `populus package install owned==1.0.0`
    - [ ] `dapple pkg package install .` to install all project dependencies
  - [ ] handle case where package is already installed.
  - [ ] handle upgrading already installed dependencies
- [ ] creating and publishing releases
  - [ ] `dappke pkg publish`
    - [x] publish to ipfs
    - [ ] publish to registry

**Comment by tcoulter** [comment]
Should we work together on https://github.com/ethpm/ethpm-js? Documentation is currently wrong, but it's tool independent.

**Comment by mhhf** [comment]
@tcoulter I had a look on ethpm-js a week ago or something and I think we could indeed collaborate on some parts, but I have concerns about switching completely to this repo as dapple does a few things fundamentally differently: e.g. it has a Dappfile, which describes a multi chain environment, therefore we don't have a manifest file on the hard drive, which you assumes during publishing.

If you are fine with me, refactoring/ parameterizing those parts, I'll definitively have a second look on it over next days.

**Comment by pipermerriam** [comment]
@mhhf please feel free to re-open if you still want to track progress here.
