### ISSUE TITLE
Truffle (via ethpm-js) implementation progress

### ISSUE THREAD

**Issue by tcoulter** [ethpm/ethpm-spec#34]
- [x] initialize `epm.json`
  - [x] cli command to populate fields with prompts
  - [ ] handling for if the `epm.json` is already present.
- [x] package installation
  - [x] cli commands.
    - [ ] `truffle install ipfs://Qm....`
    - [x] `truffle install owned` and `truffle install owned==1.0.0`
    - [x] `truffle install .` to install all project dependencies
  - [x] recursively install dependencies of dependencies
  - [ ] handle case where package is already installed
  - [ ] handle upgrading already installed dependencies
  - [x] handle conflicting dependencies (solc-js specific need)
- [x] package publishing
  - [x] `truffle publish` to IPFS and Registry
    - [x] publish sources
    - [x] publish `build_dependencies`
    - [ ] publish `contract_types` and `deployments`
      - [ ] library linking
      - [ ] deployed objects

**Comment by pipermerriam** [comment]
@tcoulter feel free to re-open if you still plan to track progress here.
