### ISSUE TITLE
Draft EIP

### ISSUE THREAD

**Issue by pipermerriam** [ethpm/ethpm-spec#45]
While I expect this repository will be the place that the spec lives for the foreseeable future, once we've frozen the V1 spec it should be codified into an EIP.

**Comment by VoR0220** [comment]
Is that necessary?

**Comment by pipermerriam** [comment]
No, and it doesn't have to happen immediately either.  Do you see a reason not to formalize it via the EIP process?  

Also, I think this fits into the ERC category since it has nothing to do with the protocol.

As an aside: looking at the EIP format, the spec document will largely be able to be copy/pasted into the EIP template.

**Comment by VoR0220** [comment]
Thats fair. Gets the people going. Increases visibility and benefits all of us.

**Comment by pipermerriam** [comment]
This was done.
