### ISSUE TITLE
Add convention for keywords

### ISSUE THREAD

**Issue by pipermerriam** [ethpm/ethpm-spec#56]
If we want keywords to be useful we should write up some text on standard conventions.  Anyone have strong opinions about this or an existing standard they know about?

**Comment by VoR0220** [comment]
Hmmm...might need to explain your thoughts here a tad.

**Comment by tcoulter** [comment]
I assume Piper's referring to things like "they should be all lowercase".

**Comment by pipermerriam** [comment]
You assume correctly.

**Comment by VoR0220** [comment]
Sure....i guess...send up a PR

**Comment by emprisupriatna** [comment]
Okey

**Comment by gnidan** [comment]
What's the current status of this? Seems like it's done
