### ISSUE TITLE
Change all URIs to use a generic content addressable URI

### ISSUE THREAD

**Issue by pipermerriam** [ethpm/ethpm-spec#66]
### What is wrong

Currently the specification uses IPFS uris for all external references.  This is not extensible as it would require spec changes to support any new URIs (such as swarm)

### How can it be fixed

In all places in the spec where we specify an IPFS uri, change the language to specify that the URI must be content addressable and provide a short list of recommended URI schemes that tooling should support (currently IPFS and swarm)

**Comment by VoR0220** [comment]
Definitely agree with this. This is not extensible and is a little too strict.

**Comment by tcoulter** [comment]
:+1: as well
