### ISSUE TITLE
Recommended metadata for linking to audits

### ISSUE THREAD

**Issue by pipermerriam** [ethpm/ethpm-spec#68]
### What is wrong

Code audits for smart contracts are a thing.  It would be good if we at least had a recommended key and format for linking to smart contract audits in the metadata section.

### How can it be fixed.

We can recommend people include audit information under the key `security-audit` in the `meta` section.  The value under this key should be *either* a singe object, or an array of objects.  These objects should have a key `type` under which we recommend using either `text` or `uri`.  The object should also have a key `value` under which either the full content of the audit can be embedded *or* if `uri` a content addressable URI of the content.

We should also recommend that any referenced audits should be cryptographically signed to ensure authenticity.

**Comment by VoR0220** [comment]
Not sure if this belongs in the meta. Could be wrong but I think there might be a better solution. I'm just not sure what.

**Comment by Hackdom** [comment]
I wonder if this would be something also suited for the index contract. Auditors would be able to post the uri for their audit of a particular library in the index. Again the sender provides a sort of validation of who posted it. This would essentially create an audit 'repo' for all libraries in the given index.

**Comment by gnidan** [comment]
(closing, won't fix)

Reasoning: this is a perfect candidate for second-layer solutions. Given a federated model for package registries, package audits could be identified by auditor-maintained "package mirror" registries.
