### ISSUE TITLE
Add specification for link references in bytecode and runtime_bytecode

### ISSUE THREAD

**Issue by pipermerriam** [ethpm/ethpm-spec#69]
Currently, link references are only inferrable from the bytecode by inspecting it and looking for things that match the regex for `___ContractTypeName_____`.  These should be instead specified precisely by using the *offset*, *length*, and *name*.

**Comment by VoR0220** [comment]
Do you think this is a little overkill with the advent of JSON I/O?

**Comment by pipermerriam** [comment]
@VoR0220 no, I don't think so.  There are a lot of similarities between this spec and the standard json compilation but I don't believe they serve the same purpose and I'd like to keep them separated for now (though we can absolutely borrow from that spec).

**Comment by Hackdom** [comment]
This is good, although are we anticipating lengths greater than 40 characters?

**Comment by pipermerriam** [comment]
Currently spec is set to permit lengths up to 256 characters.  Character limit isn't the only problem here though.  Link references will not always be 20 byte addresses.  Consider the following.

```
0x1234__Thing____abcd____beef010203
```

* Is that one link reference with the name `Thing____abcd`
* Or is it two: `__Thing__` and `__abcd____`

**Comment by VoR0220** [comment]
Good point. Okay. That example alone seals it for me. Lets pop this in there.

**Comment by pipermerriam** [comment]
> Although to be fair, current Solidity linking does specify the filename

Which results unlinked code that looks like this if you have file paths that are even a little long.

```
0x1234__contracts/some-folder-depth/C__abcd
```

It truncates the path to 36 characters which often results in you seeing a bunch of directory prefixes that all look the same.

**Comment by VoR0220** [comment]
Fair enough.
