### ISSUE TITLE
IPFS Clients?

### ISSUE THREAD

**Issue by ccorcos** [ethpm/ethpm-spec#79]
Can you recommend any IPFS clients for Mac that use the `ipfs://` protocol?

**Comment by pipermerriam** [comment]
https://ipfs.io/docs/install/

**Comment by ccorcos** [comment]
I downloaded that but there doesnt appear to be an application that registers the ipfs protocol. I cant click it and download something.

**Comment by pipermerriam** [comment]
@ccorcos I'd recommend heading over to the IPFS github and seeing if they can help you further https://github.com/ipfs/go-ipfs
